version: '3'

services:
    upload:
        build:
            context: .
            dockerfile: Dockerfile.test
        ports:
            - 8010:80
        environment:
            - AWS_ACCESS_KEY_ID=$ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY
            # - S3_ENDPOINT="https://fra1.digitaloceanspaces.com"
            - DIRECTORY=testing-filepond/
            - BUCKET=testshitkjhdgfslkjsdbf
            - REGION=eu-west-1
        