version: '3'

services:
    upload:
        build:
            context: .
            dockerfile: Dockerfile.test
        ports:
            - 8010:80
        environment:
            - ENDPOINT=https://storage.googleapis.com
            - AWS_ACCESS_KEY_ID=$ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY
            - DIRECTORY=testing-filepond/
            - BUCKET=efi-archives
            # - REGION=eu-west-1
        