name: Python package


on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    # - name: Test with pytest
    #   run: |
    #     pip install pytest
    #     pytest
    - name: Publish to Dockerhub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: xmorse/s3-filepond
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Bump version
      uses: remorses/bump-version@master
      with:
        version_file: VERSION
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



    
    
    
    
    
    
    
    
    
    
    
